### ISSUE TITLE
User auth via facebook

### ISSUE THREAD

**Issue by mmahalwy** [quran/OneQuran#1]
- [x] Create users table
- [x] Create Facebook app
- [x] Omniauth strategies for both

**Comment by mmahalwy** [comment]
I am thinking maybe twitter is part of the wish list, but e/p + facebook might be more important

**Comment by maryamklabib** [comment]
And specifically, e/p first

**Comment by mmahalwy** [comment]
re our conversation, @maryamklabib we will do facebook first
